### ISSUE TITLE
Log is larger than the game in mobile

### ISSUE THREAD

**Issue by rzulian** [boardgamers/gaia-viewer#102]
![img_e162eb0beb95-1](https://user-images.githubusercontent.com/29941924/46226351-45304900-c35c-11e8-9995-5f74c1226f0f.jpeg)

**Comment by coyotte508** [comment]
Game name, so I can check easily?

Also maybe this would be improved by using the icons for faction name, and hiding the faction names on mobile.

**Comment by rzulian** [comment]
https://gaiaform.io/game/Fastgame01
