### ISSUE TITLE
Ivits space station are not displayed on the faction board as satellites

### ISSUE THREAD

**Issue by Zevenberge** [boardgamers/gaia-viewer#160]
Just a minor bug: the faction boards are now self-contained and contain basically all information of the game. However, Ivits' space stations are not counted towards the satellites. It would be nice if the count on the board matches the one for the end goal.

**Comment by coyotte508** [comment]
Hey @Zevenberge !

I saw your comment on discord and decided to implement it in https://github.com/boardgamers/gaia-viewer/commit/78b7610f5377934d1550ac22cea4e214e62918c6. Then when I went on github to trigger the release & publish, I saw your issues and PR! 😅

**Comment by Zevenberge** [comment]
No probs :) Thanks for fixing it.
